### ISSUE TITLE
Game save doesn't appear to work.

### ISSUE THREAD

**Issue by the-importer** [MiSTer-devel/GBA_MiSTer#1]
Hi there,

Before we begin, great work on this core, it's amazing to run GBA on a TV without software emulation or a GameCube. Now regarding the saving issue, I tried 2 games so far (Metroid Zero Mission and Kirby and the Amazing Mirror) and they both won't load save data after a cold or a warm boot. I tried with the official BIOS, didn't change anything. I tried the auto-save function as well as the manual and reload function ,  still didn't work.

Is this an issue with the core or am I doing something wrong?

**Comment by sorgelig** [comment]
i know.
i'm investigating.

**Comment by the-importer** [comment]
> i know.
> i'm investigating.

That's cool man, just trying to help.

**Comment by MP2E** [comment]
This is fixed, can be closed
