### ISSUE TITLE
Feature request- both instances able to boot up with common save both carts 

### ISSUE THREAD

**Issue by Sarvets** [MiSTer-devel/GBA_MiSTer#104]
I was playing hajime no ippo and seen that the stuff i unlocked was only available on the same instance of the game I was unlocking things on, while 2p was stuck no able to load anything as far as unlocks. would it be possible to have both games just load the same save? I feel this would be a great feature for GBA 2p because both players would have access to whatever could be unlocked in the various Multiplayer games

**Comment by RobertPeip** [comment]
implemented
