### ISSUE TITLE
Feature request - Dual CRT

### ISSUE THREAD

**Issue by stainmage** [MiSTer-devel/GBA_MiSTer#106]
Hello, it would be nice if it was possible to output both analog and hdmi at the same 240p resolution to use 2 crt, this can be achieved with direct video option, but it clones the analog output to hdmi, and the core doesn't handle it to draw screen 1 if used.

Cheers

**Comment by RobertPeip** [comment]
This doesn't work so easily, as the HDMI output comes from a direct framebuffer access of the scaler, unlike the VGA output of core 2. 
Changes here would be required to do in the framework part and with that would effect ALL cores, which is by far not worth the effort.
Therefore i will not add this.
Sorry.

**Comment by stainmage** [comment]
wouldn't be possible to use the vga scaler with direct_video=0 to scale the hdmi output to sync with crt ? I managed to make it fit on the analog screen, but for some reason the hdmi out didn't sync

**Comment by RobertPeip** [comment]
It's likely possible somehow, but not planned or made for that. This is a lot of effort for a very niche feature and I don't really want to spend time for that and maintain it. GBA2P core should be as close as possible to normal GBA core or it will be a nightmare to maintain.
