### ISSUE TITLE
Metroid - Zero Mission (Virtual Console) Fails to Load

### ISSUE THREAD

**Issue by JaydeSix** [MiSTer-devel/GBA_MiSTer#107]
Using official BIOS Metroid - Zero Mission (Virtual Console) shows a white screen after the BIOS startup. Confirmed hash against No-Intro (8825294A). Retail version loads fine. Also tried a couple other Virtual Console game versions (Castlevania - Circle of the Moon, Castlevania - Aria of Sorrow) and they load correctly.

**Comment by Jayde6** [comment]
Might want to add VC games to the unsupported part of the github page, we just had another user on the discord get a game freeze later into the game with the VC version of Castlevania Circle of the Moon. They loaded a save they had made before the freeze and were able to proceed fine with the retail version of the rom.
