### ISSUE TITLE
F-Zero Climax - regression

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/GBA_MiSTer#109]
Current build of the GBA core (20210718) has a visual bug which was previously fixed (issue #73). Bug appears in both the original Japanese game and the recent English translated version. Checking previous releases of the core revealed that this bug reappeared in release 20210629.

**Comment by RobertPeip** [comment]
So you checked 20210629 = bug present and 20210415 = not present?
That would be strange, as there is nothing in between that should ilfluence it.

Maybe it's more a random effect depending on how the core boots up the first time or something like that?

**Comment by Thelypody** [comment]
That's right — 20210415 behaves properly while 20210629 has a visual bug. This happens consistently on my setup with default core settings.

**Comment by RobertPeip** [comment]
Ok, can reproduce it. Will rebuilt the different versions and see where it changes.

**Comment by RobertPeip** [comment]
Issue comes back with this commit:
https://github.com/MiSTer-devel/GBA_MiSTer/commit/aaa82231bb6fbf80f4bff7d18c84e966d68a7fdd

This is not directly related, but does some slight changes on the Registerbus.
Most likely the synthesis handles the Registerbus different with that change.

Unfortunatly the GBA core still uses my old method of a tri-state register bus which e.g. behaves different already with different Quartusversion and likely more constraints.
Maybe I exchange it to wired-or like i use in all the other cores to be more reproducible some day.
Most likely when I have to port the core to another FPGA.

For now, I see no fast way of fixing this, sorry.

**Comment by RobertPeip** [comment]
Fixed, see:
https://github.com/MiSTer-devel/GBA_MiSTer/issues/76
