### ISSUE TITLE
Doom:  Glitches on top left corner. 

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/GBA_MiSTer#11]
This was first noticed during Smokemonster's recent stream.  It appears to be random pixels going black.  Overall the game is playable and the bug is minor, but thought I'd still make this known.

https://youtu.be/XEEm6cQ49qo?t=5704

**Comment by RobertPeip** [comment]
could be that missing feature i guess:
https://github.com/RobertPeip/FPGBA/issues/7

**Comment by RobertPeip** [comment]
fixed
