### ISSUE TITLE
Mo Jie Qibing trips copy protection 

### ISSUE THREAD

**Issue by uncletrunks** [MiSTer-devel/GBA_MiSTer#110]
This is an unlicensed-but-original game from Chinese developer Vast Fame. Vast Fame's GBA games (Mo Jie Qibing, some Zook Man games, Digimon Ruby, etc) used copy protection. This copy protection is currently supported exclusively by [mGBA](https://github.com/mgba-emu/mgba/blob/master/src/gba/cart/vfame.c), but is pretty well documented in their source.

**Comment by RobertPeip** [comment]
I researched that a bit a while ago and decided the bus scrambling doesn't fit well in the FPGA.

It's probably better to wait for someone to decrypt the ROMs statically.
