### ISSUE TITLE
Feature Request: Option to mute/fade out audio when fast forwarding

### ISSUE THREAD

**Issue by FarawaySounds** [MiSTer-devel/GBA_MiSTer#111]
I use the fast forward feature quite often and have found the audio distortion when fast forwarding distracting. If there was an option to fade out or mute the audio when doing so that'd be an amazing addition.

**Comment by RobertPeip** [comment]
As WonderSwan and Lynx also have these options, it would be good to have it in GBA, too.

If you like, you can do yourself and submit a pull request. You can look how it's done in Lynx, it's really easy:

"OP,FastForward Sound,On,Off;",
+
assign AUDIO_L = (fast_forward && status[25]) ? 16'd0 : Lynx_AUDIO_L;
assign AUDIO_R = (fast_forward && status[25]) ? 16'd0 : Lynx_AUDIO_R;

It's the same for GBA, you just need to use a free status bit as 25 is already used in GBA and create wires for GBA_AUDIO_L and _R.

If you cannot do that, i fear you have to wait until i have time again.
