### ISSUE TITLE
Rumble: Additional Titles

### ISSUE THREAD

**Issue by ValadAmoleo** [MiSTer-devel/GBA_MiSTer#122]
The following titles are rumble enabled on the Game Boy Player:

Mario & Luigi: Superstar Saga
Pokémon Pinball: Ruby & Sapphire
Super Mario Advance 4: Super Mario Bros. 3

I’m guessing this is different to the way rumble works with native GBA cartridge hardware BUT there are the following patches available which allows them to work on GBA ROM cartridges. I’m not sure if this is something specific for the ROM carts but they do mention that they’d work with any rumble ROM cart. So it’s at least not using a specific API.

https://www.romhacking.net/hacks/6065/
https://www.romhacking.net/hacks/6256/
https://www.romhacking.net/hacks/6234/

**Comment by RobertPeip** [comment]
New feature available in OSD. Tested rumble working with SMA4 romhack.
