### ISSUE TITLE
Setting "Sync core to video" to Off makes core unusable on next launch

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/GBA_MiSTer#123]
By default core has a setting "Sync core to video" to On. Disabling that setting and loading roms after keeps core operating normally, but saving settings, exiting the core and loading it again from the Menu produces only a blank screen on a 15khz CRT display connected though an Analog IO board. Pressing F12 to open core menu does not display any picture, leaving erasing core settings as a only solution.
I tested it with an HDMI display connected simultaneously with an analog display, and on LCD display core draws a "noise" image while the CRT stays blank. It is possible to load a rom on LCD but the core will not start a game until the "Sync core to video" setting is enabled.
I remember having no issues leaving that setting disabled of some old revisions, as the core would boot GBA bootrom automatically. For some reason it doesn't do so anymore unless the core is synced to video.

**Comment by Thelypody** [comment]
Digging though old releases, 20210415 has the setting set to Off and the core works fine with both options saved. The next release, 20210629, switched the default value to On and disabling it and saving leads to behavior explained above.

**Comment by RobertPeip** [comment]
fixed
