### ISSUE TITLE
Core pads save data for Pokemon Ruby/Sapphire/Emerald

### ISSUE THREAD

**Issue by coltmay** [MiSTer-devel/GBA_MiSTer#124]
Not entirely a bug, but for the sake of accuracy, .sav files for 3rd Gen Pokemon games (barring FireRed and LeafGreen), are padded, coming out as 132KB rather than the intended 128KB.  This causes issues when using saves across devices.

**Comment by RobertPeip** [comment]
This is intended as those games contain additional data for Real Time clock.
