### ISSUE TITLE
After long play sessions with fast-forwards, game eventually corrupts and freezes/crashes

### ISSUE THREAD

**Issue by Drakonas** [MiSTer-devel/GBA_MiSTer#127]
I've only mainly played two games that are hacks on the GBA using the fast-forward feature a lot: Pokemon Emerald Double Plus and Mega Man Battle Network 3 randomizer. But I have also noticed freezes when using fast-forward sparingly after long sessions with Yu-Gi-Oh GX Duel Academy (No-Intro clean dump).

After very long (hours) play sessions, when using fast forwarding at all, it seems timing bugs occur that eventually cause the game (without notice) to crash and burn.

Mega Man Battle Network 3 randomizer crashed while it was transitioning between maps. At one other time, the music was also messed up where certain notes were not playing. Attempting to reset the core froze the entire core up. (Even the menu froze for a bit)

**Comment by RobertPeip** [comment]
I played through Firered at least 5 times with FF on all the time and never noticed any problem.
Same goes for many other games, as i use FF very often.
FF doesn't alter the timing and as the display output is independent of the framerate i cannot imagine what the problem shall be.

I don't say it's impossible, but i doubt it's a general bug of the feature, considering it was never reported and i haven't seen it in 50h+. 

Overall it sounds more like SDRAM issues.
Did you ever try to run with DDR3 to rule that out?

**Comment by Drakonas** [comment]
@RobertPeip I'll mention this here, but is it possible it is my De10-nano.

If it was the SDRAM, could the SDRAM make the GBA2P core output 1920x1080@44.5Hz through the HDMI port:
![Screenshot](https://media.discordapp.net/attachments/811089485495402497/972195336846188604/unknown.png?width=864&height=468)

**Comment by Drakonas** [comment]
I think the longplay issues were due to a bad ram seating as far as I can tell. I still get weird audio glitches here and there. Not really sure but I think it may be something wrong with my De10-Nano at this point. I can close this.
