### ISSUE TITLE
[GBA2] 2 player separate audio.  

### ISSUE THREAD

**Issue by douglie007** [MiSTer-devel/GBA_MiSTer#129]
Is there a way to make the audio from the 2 GBAs go to different places?  It would be nice to have one go to HDMI and the other go to the 3.5mm port so both players can have there own audio.  One on TV one on Headphones.

**Comment by RobertPeip** [comment]
This is currently not supported by the framework and not worth to add just for this core. You can however set both players to seperate left/right and use a splitter or mute left on hdmi and right on 3.5mm

**Comment by douglie007** [comment]
OK thank you.
