### ISSUE TITLE
Feature Request: GBA 2P Color Optimizations

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/GBA_MiSTer#132]
I love using the color optimization options on the GBA core. I use NDS 1.6 btw. It makes the GBA a lot more appealing than the oversaturated stock settings. I understand this was removed from the GBA 2P core bc it took up extra space when the GBA 2P core needs as many free resources as possible. Is it possible that this can be the only feature that's added back, please? It would just make the screens look a lot better imo

**Comment by RobertPeip** [comment]
The shader colors are too big to add them back, sorry, it will not fit
