### ISSUE TITLE
Goodboy Galaxy rumble

### ISSUE THREAD

**Issue by DanTheMan827** [MiSTer-devel/GBA_MiSTer#139]
This game supports rumble, the ID is 2GBP.

I'm not sure if there's anything else that needs to be done other that adding the quirk, but there is a "rom hack" that changes the ID to Drill Dozer that makes it work.

**Comment by RobertPeip** [comment]
Did you try to enable it yourself?
In misc -> GPIO HACK(RTC+Rumble) -> On

I think it's ok for a non-official title to activate it yourself and not have all added to the list, as the list is not free but will cost logic.

**Comment by pomstazlesa** [comment]
Rumble works correctly with GPIO HACK(RTC+Rumble) ON, without needing to change the ID to Drill Dozer.

**Comment by RobertPeip** [comment]
Thank you, I will close this then.
