### ISSUE TITLE
Fastforward gives "Out of Range" with my monitor

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/GBA_MiSTer#15]
I'm using vsync_adjust=1.
I completely lose sync when using fastforward, with or without "Sync core to video" option.

I think this caused it:
https://github.com/MiSTer-devel/GBA_MiSTer/commit/6c9c93f6e619f256a18ab61e9788c9d2f730c7eb

Was working alright before this commit.

**Comment by MP2E** [comment]
Can confirm, happens on my monitor too

**Comment by cacophony1** [comment]
I see a similar issue with vsync_adjust=2 and the latest commits. Worked well until I tried fast forward, at which point the core became unusable until it was reloaded.

**Comment by James-F2** [comment]
Fixed.
