### ISSUE TITLE
Feature Request: half screen size over HDMI

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/GBA_MiSTer#17]
For the lack of a better place, I would like to request a half size screen option as part of the "aspect ratio" sub menu for HDMI output.
To me, it seems even my 22" monitor is much too big for such low resolution console.
Looks fantastic on CRT with smaller centered image.

**Comment by sorgelig** [comment]
use LCD filter. 
I don't remember anyone complain about Gameboy core which has even lower resolution.
You can add border size in ini file to make it smaller.

**Comment by James-F2** [comment]
Alright, 
No complaint, just feature request.
Can be closed if useless.

**Comment by James-F2** [comment]
ini border capped to 99.
Need more.

**Comment by sorgelig** [comment]
I think limit can be increased. I will check.
