### ISSUE TITLE
Pokemon Fire Red reports dead battery and does not save

### ISSUE THREAD

**Issue by malfunct** [MiSTer-devel/GBA_MiSTer#21]
The game plays fine but when it starts up I get a notice that the game battery is dead and when I use the save feature in game and then restart the game there are no saved games to load.

**Comment by James-F2** [comment]
Saves fine here.
You have to open the OSD for mister to save into a .srm file.

**Comment by RobertPeip** [comment]
Saves fine on my hardware and mister, cannot reproduce. I don't even get the message. Only saphire has this message, but that's because of rtc it seems and it still saves ok.

Please check again, maybe with other rom/bios.

**Comment by James-F2** [comment]
I did have this message for the very first time I booted the Fire Red rom.
But after saving, the message is no more.
Not a bug, can be closed.

**Comment by malfunct** [comment]
I have successfully saved. There needs to be better documentation on this than "saves as on gba" in the readme.
