### ISSUE TITLE
Top Gun - Combat Zones needs to ignore all save types

### ISSUE THREAD

**Issue by greyrogue** [MiSTer-devel/GBA_MiSTer#27]
I noticed the addition of sram quirks.  Just wanted to mention the one that stood out to me the most when I was working on GBA stuff.  Top Gun - Combat Zones is listed in the Readme as not working.  I'd guess that's because it needs some quirks.  It actually tries to write all three methods of saving, but doesn't actually have any hardware to save.  If the save succeeds for any of the methods, the game breaks. https://zork.net/~st/jottings/GBA_saves.html

**Comment by RobertPeip** [comment]
Tested with my emulator:
prevent sram write is enough for this game to work, eeprom save does not need to be prevented.

I can add the game to the exception codes the next days. (or anyone else can do)
