### ISSUE TITLE
Rhythm Heaven: Samurai Slash background effects wrong

### ISSUE THREAD

**Issue by RobertPeip** [MiSTer-devel/GBA_MiSTer#29]
![grafik](https://user-images.githubusercontent.com/53250236/70888911-aab03a00-1fe1-11ea-9c02-5c22d312564e.png)

right lower edge

**Comment by Optiroc** [comment]
Fixed as of b62376b2ad261c4d0060eab504639cdc47b6fe24 👍

**Comment by RobertPeip** [comment]
thanks for testing!
