### ISSUE TITLE
Doom II - Vertical Lines in ceiling and floor

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/GBA_MiSTer#3]
![Screenshot from 2019-11-24 21-56-53](https://user-images.githubusercontent.com/167708/69516125-95298200-0f05-11ea-8ab0-34cfd476ba41.png)
Confirmed by a few users, figured it was worth posting

**Comment by RobertPeip** [comment]
Already checked my emulator, It's working there.
With a romhack that instantly boots ingame this can probably be fixed easy.

**Comment by Hewhoisred** [comment]
Strangely, Doom 1 does not have this problem, but Duke Nukem 3D does.  I will try to check all the other FPS games on the system and report here.

**Comment by RobertPeip** [comment]
fixed
