### ISSUE TITLE
Street Fighter Alpha 3:   Graphics Glitch - Options Highlight

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/GBA_MiSTer#31]
Highlighted options in this game are displaying incorrectly, and covering up the name of the option that is selected:
![gba sfa3 menu bug](https://user-images.githubusercontent.com/40709481/71375191-06029f00-2583-11ea-9baa-6c0f728320e4.PNG)

The original behavior of the game allows you to see the white text of the selected option instead of this opaque green box covering it up.

**Comment by Eyedunno** [comment]
For reference, here is what this is supposed to look like:

**Comment by Eyedunno** [comment]
For reference, here is what it is supposed to look like:
![80352531_2955058501184379_607403805532749824_n](https://user-images.githubusercontent.com/45522237/71427168-06299a00-266a-11ea-97a8-a599a8ba61e6.jpg)

**Comment by RobertPeip** [comment]
Please verify, should be fixed with the new release.

**Comment by M-Walrus** [comment]
Confirmed this is fixed in 20200101 release. Closing issue.
