### ISSUE TITLE
Glitchy Rows of Pixels in Many Games (SSF2T, Advance Wars, etc)

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/GBA_MiSTer#32]
Glitchy rows of pixels showing up in many games.  Current workaround is to turn turbo CPU on to clear this up.

The following examples have been noted/recorded:  EDIT: NOW FIXED - **See below posts for existing issues.**

Super Street Fighter 2 Turbo: Revival - at the top of DeeJay's Stage, and on e-honda's stage: https://youtu.be/_u_NGNtMlrc
Watch the top-left corner of the bath in the background while i walk back and forth, at the base of the mountain, to see a glitchy blue line of pixels come and go.  There is also a glitchy line of pixels on the ground, which seems to be on every stage.

Advance Wars - Glitchy row of pixels at the top of the text box, as shown here: https://imgur.com/a/8WFIH4B

EDIT: Both of these are now fixed, or confirmed behavior on actual gba - **See below posts for existing issues.**

When I turn Turbo CPU on, as suggested by the core author in Discord, all of these graphical glitches go away, as shown in the SSF2T video.

**Comment by RobertPeip** [comment]
Additional note: Instruction cycle accuracy bug. Some of the current instruction times are too long and these are VERY frequently used in this games. If i shorten every instruction cycle time by 2, these effects are gone, 1 is not enough.

We need to fix more "Timing" tests in suite.gba to solve this issue. Until then CPU Turbo seems to be a good workaround.

**Comment by RobertPeip** [comment]
I will maintain a list of these games here. If you have any news, please post and i will add/remove it.

Acrobat Kid (Japan)
Advance Wars
Super Street Fighter 2 Turbo: Revival

**Comment by RobertPeip** [comment]
All the issues listed here are now gone as far as i tested. Please confirm, so it can be closed

**Comment by mathieulh** [comment]
No more issues in Advance Wars for me.

**Comment by sorgelig** [comment]
Phalanx glitching lines in clouds parallax. Is it the same issue?

**Comment by SegaSnatcher** [comment]
> Phalanx glitching lines in clouds parallax. Is it the same issue?

If its what I think you are talking about those glitchy lines happen on a real GBA too.  I just tested with my backlit GBA 101.

**Comment by sorgelig** [comment]
Oh, i see..

**Comment by Optiroc** [comment]
Super Street Fighter 2 Turbo: Revival:
The "pool glitch" on Honda's stage and the top line glitch on DeeJay's stage are gone, so the issue can be closed.

I did however confirm the observation that on some stages the parallax floor will flicker on 1-2 lines while on certain (x-scroll) locations. This may be present on real hardware too, so it needs to be confirmed and can possibly go in a future issue if so. I observed the glitch on Honda's, Guile's and Chun-Li's stages (but I didn't check all the stages).

**Comment by RobertPeip** [comment]
wwark has found some more glitchy lines in the newest release. I lwill update the status tomorrow.

**Comment by wwark** [comment]
Glitches issues or missing line and graphics

Iridion 3d - Glitches at the game over screen - not present in real hardware - save state : 
[Iridion 3D (USA, Europe).zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/4130122/Iridion.3D.USA.Europe.zip)

**Comment by M-Walrus** [comment]
I see Iridion 3D was already reported. I was just about to report it but checked here first. 
Here are two places where you can see the glitchy line in Iridion 3D. First is actually right at the beginning (Developer Logo) and seems the same as the "game over" screen example. Top row of pixels in each example is shifted far to the left:

Logo: https://youtu.be/WWyJugZctRY?t=45

Game Over: https://youtu.be/WWyJugZctRY?t=1500

**Comment by RobertPeip** [comment]
Those affine effects in Iridion really depend on correct instruction timing, as they have a fixed sample point for the affine parameters. 
I don't want to shift the sampling point, as that would influence other games and i don't see instruction timing improve anytime soon. Sorry.

**Comment by paulb-nl** [comment]
That glitchy blue line at E. Honda's stage also appears on real hardware although in a different way. So having no glitch at all is also inaccurate.

https://youtu.be/Z4QV8cF2ez0?t=127

**Comment by Chocobobobo** [comment]
Now that we have a shiny core thanks to Robert's efforts, can you recheck wwark? Thanks!

**Comment by wwark** [comment]
Already check them but those issues are still present. Thanks !

**Comment by RobertPeip** [comment]
wwark has opened new tickets for all the problems that remain out of this long entry, so i close here.
