### ISSUE TITLE
[Regression] Fire Emblem Portrait screen is erroneously darkened

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/GBA_MiSTer#36]
This bug was introduced as in #35 

![Screenshot from 2019-12-31 03-47-02](https://user-images.githubusercontent.com/167708/71620838-ecfc7e00-2b80-11ea-974e-2ac4b1fc0ebd.png)

Here's what it should look like:

![Screenshot from 2019-12-31 03-48-58](https://user-images.githubusercontent.com/167708/71620855-f8e84000-2b80-11ea-8c08-da7e118d3634.png)

The 2nd picture is taken from the GBA core, but a real GBA or Game Boy Player looks the same(minus the font issues, which are tracked in another issue)

**Comment by paulb-nl** [comment]
Fixed by #37
