### ISSUE TITLE
Feature Request: Cheat Engine Support for GBA

### ISSUE THREAD

**Issue by crealdocsnyder** [MiSTer-devel/GBA_MiSTer#39]
Well, it is all in the title. Cheat support for GBA would be huge for people like me who have not enough time but would like to experience the amazing library of the GBA with some help.
The Cheat Engine is an amazing feature for cores that have it implemented and it would make the GBA core even greater than it already is.

**Comment by rimsky82** [comment]
The cheat engine already integrated with the other MiSTer cores is simplified, and doesn't quite handle the complexity of the original GBA cheat devices.  There has to be a better solution, and I believe it is planned at this point.

**Comment by sorgelig** [comment]
It will be implemented when it will be implemented. There is no point to request obvious things.
