### ISSUE TITLE
mGBA Test Suite - regressions in MiSTer core compared to original core

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/GBA_MiSTer#4]
I noticed there are some regressions in the number of tests that pass vs the original core, and wanted to track that in this bug report. This seems like more of a longer term milestone, rather than something to be quickly fixed.

Here's how it currently stacks up:

Testname | TestCount | FPGBA | MiSTer
---------|-----------|-------|-------
Memory   |      1552 |  1538 | 1532
IOREAD   |       123 |   123 |  108
Timing   |      1660 |  1408 | 1408
Timer    |       936 |   443 |  443
Carry    |        93 |    93 |   93
BIOSMath |       625 |   625 |  625
DMATests |      1256 |  1136 | 1112 

[mGBA Test Suite can be found here](https://github.com/mgba-emu/suite)

EDIT: Corrected "Timing" numbers

**Comment by sorgelig** [comment]
i think you are wrong about  Timing 1308

I get 1408 on my MiSTer.

**Comment by MP2E** [comment]
I retested and it is 1408, I must have made a typo

**Comment by RobertPeip** [comment]
IOREAD is because of quartus synthesizing different. I will fix this as i have my sdram board here.
Maybe other differences are fixed then, too.

**Comment by RobertPeip** [comment]
fixed, current build fulfills the same tests as FPGBA(DE2-115 implementation)
