### ISSUE TITLE
Feature request: Load GB/GBC games in GBA core

### ISSUE THREAD

**Issue by Wolf-lbh** [MiSTer-devel/GBA_MiSTer#40]
There are games like Legend of Zelda Oracle of Ages and Legend of Zelda Oracle of Seasons which have added ingame extras if played on a gba. It would be great if this core could support playing those games so it would be possible to access those extra features.

**Comment by RobertPeip** [comment]
Supporting GB/GBC would mean that more of less a full GBC must be implemented. The amount of things that can be reused is so small, it's easier to just not dual use them and have both cores as single.

That being said, only things like you mentioned would be beneficial when doing that and at the current point there are no plans to do it.

We can still keep it open, as it's a valid point and someday should be done. I just fear that, if no one else is doing it, it may take some years as i have other plans before that.

**Comment by sorgelig** [comment]
Are these extra features available with goomba?

**Comment by RobertPeip** [comment]
It seems these games don't need the GBA features, but instead just rely on detecting to be played in a GBA. I doubt goomba is doing that but i didn't found out info about and also i have no info yet how it is done in general, otherwise it could probably be an option for the GBC core.
However, there are already cheats available that allow you to get the extra items for these games.

**Comment by pinobatch** [comment]
It would indeed be straightforward to add to the [Game Boy core](https://github.com/MiSTer-devel/Gameboy_MiSTer):
- Use the GBA's slight modification to the GBC BIOS (or HLE it by setting the B register appropriately)
- Set a gamma curve that crushes the blacks like a real GBA does, to compensate for GBA-aware GBC games lightening their palette to compensate for the GBA's dark gamma

**Comment by RobertPeip** [comment]
Considering the size of the GBA core and the GB core, they will not fit into the De10-Nano FPGA at the same time, therefore it cannot be done on this platform without dropping other features from the core.
I will close this.
