### ISSUE TITLE
Gunstar Super Heroes: Priority issues with transformed sprites

### ISSUE THREAD

**Issue by Optiroc** [MiSTer-devel/GBA_MiSTer#42]
Gunstar Super Heroes uses scaled/rotated sprites liberally, and there are priority issues with those sprites and the status bar.

![GunStarSuperheroes_Priority](https://user-images.githubusercontent.com/907446/71963699-81f41c80-31fc-11ea-867d-c78e11b91b59.jpeg)

The screenshot shows the first stage of the second level, but you can observe this bug in the very beginning of the game, when a helicopter carrying enemies appears from above.

**Comment by Optiroc** [comment]
Here's a savestate with the issue present. 
[Gunstar Super Heroes (USA).ss.zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/4034421/Gunstar.Super.Heroes.USA.ss.zip)

**Comment by RobertPeip** [comment]
The green sprite has highest prio (0) so the result seems to be correct. However, it may not be the correct size or it should not be there at all. Need to compare to real hardware or known good emulator...

**Comment by Optiroc** [comment]
As discussed, but putting it here for posterity: mGBA has the same issue, and on real hardware the black status bar is on top except for some flicker on the last line.

**Comment by RobertPeip** [comment]
option for sprite draw time limit added as opt-in

**Comment by Optiroc** [comment]
👍
