### ISSUE TITLE
Super Mario Advance crashes when selecting Super Mario Bros. in the main menu

### ISSUE THREAD

**Issue by mathieulh** [MiSTer-devel/GBA_MiSTer#43]
Super Mario Advance crashes when selecting Super Mario Bros. in the main menu

This happens in both the US and US Virtual console versions of the game.

**Comment by SegaSnatcher** [comment]
This bug was known since the GBA core was initally ported to MiSTer.  

FPGAZumSpass actually fixed this issue yesterday.  Just gotta wait for a new release.

**Comment by mathieulh** [comment]
Thanks, I will close it as soon as I can successfully test the fix :)

**Comment by RobertPeip** [comment]
i will create a new test build today and post it in discord. Still need more testers to verify nothing new broke until i do a new release, as there are a lot of critical changes done.

**Comment by mathieulh** [comment]
I just tried the test build, the issue is fixed :)
