### ISSUE TITLE
Very obvious graphical glitches in Phantasy Star collection

### ISSUE THREAD

**Issue by mathieulh** [MiSTer-devel/GBA_MiSTer#44]
Very obvious graphical glitches are present Playing Phantasy Star in Phantasy Star collection, especially in text. 

I am using the US version of the rom.

This happens in both the stable and Accuracy_fixes_10 release present on discord.

UPDATE: I just built the core from the latest sources available on github using Quartus 17.1.1, the issue still occurs.

![mfLspqn](https://user-images.githubusercontent.com/203427/72179369-0c977000-33e5-11ea-972a-5fd608a481d0.jpg)

**Comment by RobertPeip** [comment]
could be the thing that is mentioned here: https://www.ngemu.com/threads/gba-open-bus.170809/

i will check tomorrow

**Comment by paulb-nl** [comment]
The game uses DMA1 to copy from 08770E5A+ to BG1VOFS  and DMA2 to copy from BG1VOFS to BG0VOFS. 

BG1VOFS is write-only and according to a comment at that ngemu.com link it should copy the value last read by DMA1. 

> Also should note there's a phantasy star collection game that relies on DMA having its own separate open bus instance. Specifically the phantasy star 1 sub-game relies on the last valid dma write copying the value over the another dma channel's illegal read for that interlaced scanline effect.

What is currently being copied by DMA from BG1VOFS to BG0VOFS?

No$GBA has the same issue and it copies random garbage.

**Comment by RobertPeip** [comment]
ok thanks, i will check again. The shared openbus for the 4 DMAs is implemented, but maybe it still has a bug

**Comment by RobertPeip** [comment]
ok found the reason: the shared bus was ok, but for dma it was only recognizing addresses below Workram, so it would not it's own openbus for failed register reads. Will fix that later

**Comment by RobertPeip** [comment]
fixed. Game also needs interframe blending to be flickerfree, as VOFS is alternating 9 and 10.
