### ISSUE TITLE
Super Street Fighter 2 - Crash when triggering Akuma

### ISSUE THREAD

**Issue by Hewhoisred** [MiSTer-devel/GBA_MiSTer#47]
So sometimes you can trigger a cutscene with Akuma during normal play.  When this happened, the core crashed.  Music kept going and OSD works but the game is hung, see picture.

This is using the most up to date official build, 20.01.01.

![2020-01-18 (1)](https://user-images.githubusercontent.com/47957258/72672255-fce2e180-3a0b-11ea-9b49-225f48820927.png)

**Comment by Hewhoisred** [comment]
I started pressing all of the buttons I could and was able to get make out to the menu from this stuck state, and when I started up a game again the sprites had corruption.  See attached video and pic.

[2020-01-18 16-04-11.zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/4082075/2020-01-18.16-04-11.zip)
![2020-01-18 (2)](https://user-images.githubusercontent.com/47957258/72672288-901c1700-3a0c-11ea-9506-ba2d0f66999f.png)


Attached save state:

[Super Street Fighter II Turbo - Revival (USA).zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/4082081/Super.Street.Fighter.II.Turbo.-.Revival.USA.zip)

**Comment by Hewhoisred** [comment]
Just had the same crash with the latest 20200116 test build.

**Comment by Hewhoisred** [comment]
I will see if I can create a save state right before it happens.

**Comment by SegaSnatcher** [comment]
Do you have CPU Turbo off?

**Comment by Hewhoisred** [comment]
yes

**Comment by paulb-nl** [comment]
I had these corrupted cutscenes on real GBA and my save was corrupted. Try to remove your save file from the saves folder and reload the core.

**Comment by RobertPeip** [comment]
this really could to be a bug in the game itself:

https://gamefaqs.gamespot.com/gba/472721-super-street-fighter-ii-turbo-revival/faqs/16137

**Comment by RobertPeip** [comment]
it seems this really could be a bug in the game itself:

https://gamefaqs.gamespot.com/gba/472721-super-street-fighter-ii-turbo-revival/faqs/16137

"After the VS match-up
screen, Akuma's victory screen picture will show up pixel and glitched up.
The game will hang until you do a hard reset."

**Comment by Hewhoisred** [comment]
Ah, okay then.  Wow, that's unfortunate.  I guess we can close this issue then.
