### ISSUE TITLE
Font issue with Fire Emblem (The Blazing Blade)

### ISSUE THREAD

**Issue by palodich** [MiSTer-devel/GBA_MiSTer#48]
Some fonts are not displaying in Fire Emblem (The Blazing Blade). Interestingly I didn't have this issue when I first started playing the game. I think I noticed it after the update that added save states and turbo.

I've included a screenshot and a comparison with a screenshot from Higan. Look at the "I" in "Thief".

![20200105_172247-Fire Emblem (USA, Australia)](https://user-images.githubusercontent.com/4729240/72673968-e3a35a80-3a36-11ea-9ee4-6b6b1995efa5.png)

![higan](https://user-images.githubusercontent.com/4729240/72673969-e7cf7800-3a36-11ea-8a54-799163acba24.png)

**Comment by MP2E** [comment]
This actually was addressed by this commit 03f57b1da472a83c62642fb1e142ff1bddf8ef9a but the fix isn't in a release yet.

Try this build https://cdn.discordapp.com/attachments/626056221786374154/667391396512137216/GBA_2020_01_16.rbf

**Comment by palodich** [comment]
I can confirm that build fixes the issue!
