### ISSUE TITLE
Rewind capture introduces audio skips

### ISSUE THREAD

**Issue by mathieulh** [MiSTer-devel/GBA_MiSTer#49]
Regression: Between the revision 20.01.19 and the rewind version (available on discord), an issue has been introduced, when playing the "FFVIA SNES color+Sound-Opera+CAPS"  restoration hack, audio skips happen (very noticeable while playing the intro) on the rewind version which do not occur on the version from 20.01.19

UPDATE: This only appears to occur when rewind capture is on.

**Comment by RobertPeip** [comment]
Rewind capture currently has 5ms pause per second, which may lead to slight stuttering. This can be further reduced by block copies and parallel read/write.

**Comment by matthargett** [comment]
Confirmed, with a different game (Piglet’s Big Game), but also seeing a steady stream of visual glitches as well. Happens throughout the play, across all areas. Turning off rewind fixes the issue.

https://user-images.githubusercontent.com/1550766/108643451-852d8480-745f-11eb-9ad0-2148d2cfe38c.MOV

**Comment by RobertPeip** [comment]
Rewind capturing has some drawbacks mentioned in the readme, that cannot be avoided. So there is no point in keeping this issue open, as it will not change.
