### ISSUE TITLE
Setting Storage to Auto will always send to SDRAM regardless of rom size and SDRAM size

### ISSUE THREAD

**Issue by mathieulh** [MiSTer-devel/GBA_MiSTer#51]
Setting Storage to Auto will always send to SDRAM regardless of rom size and SDRAM size, this means it will attempt to write 32MB roms (such as Mother 3 for example) to a 32MB SDRAM addon, which will cause glitches.

Setting Storage to DDR3 or using a larger SDRAM addon fixes the issue.

**Comment by RobertPeip** [comment]
implemented
