### ISSUE TITLE
Video does not work in 4:3 resolutions like 1600x1200

### ISSUE THREAD

**Issue by adamyeager** [MiSTer-devel/GBA_MiSTer#54]
I'm running my Mister on a 4:3 LCD @ 1600x1200. The GBA core loads and can load games, but there is no video. Sound plays and I can hear that I'm moving through menus, but there is no video output.

When I switch to 1920x1080 or 1280x720, everything works, but on a 4:3 screen the video output is smooshed.

The video mode in my mister.ini file is:
video_mode=1,1600,64,192,304,1200,1,3,46,162

**Comment by RobertPeip** [comment]
Hopefully somebody with knowledge and screen can look into, as i cannot, sorry

**Comment by sorgelig** [comment]
HDMI clock is rated for 148MHz max. It may or may not work depending on specific build. Your video mode is 162MHz which is more than 148MHz.

**Comment by paulb-nl** [comment]
If you are using that exact video_mode then it is not so strange that it is not working.
There is a 1 at the beginning which should not be there and 162 should be 162000

**Comment by adamyeager** [comment]
I tried the video mode that @paulb-nl posted above and it works like the original one did for other cores, but the GBA core is still not showing video.

**Comment by adamyeager** [comment]
This is the monitor I'm using if anyone wants to look at the specs. Mister looks awesome on it with sharp scanlines.
https://www.amazon.com/gp/product/B07P8ZCJCG/

**Comment by paulb-nl** [comment]
Do other 4:3 resolutions work like 800x600, 1024x768?

**Comment by adamyeager** [comment]
@paulb-nl I just tested video modes 1 and 5 in the ini file and that does work! I guess the core just doesn't support 1600x1200.

**Comment by paulb-nl** [comment]
I found the problem. If you use vscale_mode=1 then it will choose a vertical height of 160x7=1120. With the 3:2 aspect ratio it will result in a 1680x1120 resolution for the scaler which is wider than the screen and it messes up the calculations.
https://github.com/MiSTer-devel/GBA_MiSTer/blob/8ac70e67b9baaa5f95fefe66ffb7989105fdb16d/sys/sys_top.v#L702-L703

For a workaround you can set vscale_mode and vscale_border to 0. You can use vscale_border but you have to make sure that the final vertical height is 1066 or less. Below is an example of integer scale 160x6 = 960. (1200-960) ÷ 2 = 120 

[GBA]
vscale_mode=0  
vscale_border=120  
video_mode=1600,44,130,206,1200,1,3,46,148500

**Comment by adamyeager** [comment]
That worked! I set the vscale_mode and vscale_border to 0 and it looks great.

Thank you so much for your help!
