### ISSUE TITLE
Super Street Fighter 2 Turbo X Revival crashes before Akuma bout

### ISSUE THREAD

**Issue by thepulserifle** [MiSTer-devel/GBA_MiSTer#57]
https://youtu.be/OMcvrvWIqms

Go to 13:09 for the moment of crash.

Can be reproduced with or without cheats used. Originally discovered without cheats, but reproduced with.

1) Start Arcade game as Ryu at Difficulty Level 3.
2) Advance to Akuma match without a loss and having a handful of super finishes.
3) Observe crash.

**Comment by SegaSnatcher** [comment]
This has been brought up before and was shown to be a glitch that happens on real hardware too. 

See this faq.

https://gamefaqs.gamespot.com/gba/472721-super-street-fighter-ii-turbo-revival/faqs/16137

**Comment by thepulserifle** [comment]
GBA ports = the worst.

Close this out. Sorry for wasting your time, folks!

**Comment by RobertPeip** [comment]
You did everything right, no reason to apologize.

**Comment by SegaSnatcher** [comment]
@thepulserifle   Could you retry using this patch?   Just curious to see if it works right with GBA core. Thanks

http://www.romhacking.net/hacks/1982/
