### ISSUE TITLE
Super Street Fighter 2 Turbo - Graphics Glitches When Activating Supers

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/GBA_MiSTer#58]
Example:
E-Honda stage the lanterns on the sides and the X that shows up on the screen when activating the super, have severe corruption for a couple seconds after activation.
There appear to be glitchy lines through the middle of the screen as well, and I noticed some of the glitchy lines in the parallax scrolling floor as well.

Does not matter which character you pick, when activating super with all of them this happens.

Video:
https://youtu.be/ytIWWUA7Z-Y

Savestate:
[Super Street Fighter II Turbo - Revival (USA).zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/4367798/Super.Street.Fighter.II.Turbo.-.Revival.USA.zip)

**Comment by RobertPeip** [comment]
Glitchy lines are due to memory access being not fast enough on Mister, maybe they are gone with turbo mode.

Flickering latern sprite is really disabled. Not sure if on purpose or by bug. Would be great if somebody could try this on real gba and see if it gets semi-transparent there. GBA has quiet some afterglow, so it may not flicker there, just change color.

**Comment by paulb-nl** [comment]
Here is a video from the Gamecube with Gameboy Player. The lantern starts flickering if you choose a turbo speed. Also glitchy lines everywhere.
https://youtu.be/Z4QV8cF2ez0

**Comment by RobertPeip** [comment]
Thanks for testing that Paul!

Now what does it mean? 
I'm not familiar with how the Gameboy Player works. Would these effects happen on a GBA, too?
Can we close this bug?

**Comment by paulb-nl** [comment]
Yeah the Gameboy Player is GBA hardware so it is the same as a GBA.

**Comment by RobertPeip** [comment]
Great. So we can probably close it. Mordecai Walrus, are you ok with it?

Funny that with faster memory access the glitchy lines are gone, maybe slightly different timing already fixes them.

**Comment by M-Walrus** [comment]
Yeah I just watched the video and am closing the issue report now. That's convincing enough for me.  I had someone test this on actual hardware before, but they must have done so at normal speed. Heh. Thanks Paulb-nl for solving this odd one.
