### ISSUE TITLE
No video with BIOS file at 720P

### ISSUE THREAD

**Issue by zomgugoff** [MiSTer-devel/GBA_MiSTer#6]
I am not getting any video when using a BIOS file at 720P. If I remove the BIOS, the built-in BIOS works. It works with the BIOS at 1080P. I'm using a 1440P monitor and I like to feed it 720P signal for clean upscaling.

As a side note, I'm seeing a lot of video signal drops. I'm not sure, but they look like they only happen when certain things happen in games. Sonic Advance and Sonic Advance 3 lose video when some of the scenes change (from cutscenes to gameplay in the demo, for example).

**Comment by SegaSnatcher** [comment]
Are you using V_Sync Adjust = 2?    It is known that the GBA core doesn't like that mode, so switch to V_Sync Adjust = 1.

**Comment by zomgugoff** [comment]
Yes, I am using v_sync adjust=2. I'll have to change it and try it out. I hope that functionality can be added later.

**Comment by RobertPeip** [comment]
please comment on this, as it's probably not a common problem, i would close it otherwise

**Comment by RobertPeip** [comment]
Outdated and no reaction from creator. Nobody else noticed problems in this case -> closed
