### ISSUE TITLE
Super Mario Advance 4 - World map music on Level 7 sounds weird...

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/GBA_MiSTer#60]
Note: This was not checked against real hardware, so it might be a false positive. If it's the case, please disregard this.

Super Mario Advance 4 (Mario 3) sounds weird in the world map for level 7. It sounds "dragged". Really weird compared to the original game on the NES or even SNES (Super Mario All Stars).

Even my wife said "what's wrong with this Mario game music" when she walked across the room! :joy: 

I have attached a savestate, if it helps.
[Super Mario Advance 4 - Super Mario Bros. 3 (USA, Australia) (Rev 1).zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/4411042/Super.Mario.Advance.4.-.Super.Mario.Bros.3.USA.Australia.Rev.1.zip)

**Comment by bootsector** [comment]
Someone at the end of this post mentioned something about world 7 map music being weird in the original hardware: https://www.reddit.com/r/miniSNESmods/comments/bcfmep/super_mario_advance_4_sound_issues/

If anyone here confirms it, I will just close this. Thanks!

**Comment by RobertPeip** [comment]
Please compare to this: https://www.speedrun.com/sma4/run/8m7nre9z
@52:10

this is a speedrun on gba(no emulator) and i assume it's that sound you describe

**Comment by bootsector** [comment]
Thanks for sending this out, @RobertPeip 

Yes, original hardware sounds horrible so I'm glad you've replicated this accurately on the GBA core! :)

I'm now closing this. Thanks!
