### ISSUE TITLE
Gradius Galaxies: freeze in second part of level 3

### ISSUE THREAD

**Issue by Lmn-San** [MiSTer-devel/GBA_MiSTer#66]
I tried 2 different roms, played in easy or normal,
When I reach the solar eclipse ( after the sun and fire lions ) level 3 second part, the game freeze and the music continue.

Tested different settings of the core it always do the same.

**Comment by RobertPeip** [comment]
If possible, please create a savestate of the effect and upload it here.

**Comment by Lmn-San** [comment]
[Gradius Galaxies (U) [!].ss.zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/4594955/Gradius.Galaxies.U.ss.zip)

**Comment by RobertPeip** [comment]
Are you using the official BIOS? For me it only hangs there with opensource(Normmatt) bios, with official i was able to beat the fire beast and enter the next level

**Comment by Lmn-San** [comment]
Yes I use the normmatt bios, sorry I totally forgot to test the bios... my bad 🤗

**Comment by RobertPeip** [comment]
ok, i will close it then
