### ISSUE TITLE
Dragon Ball Z legacy of Goku II and Buu’s Fury

### ISSUE THREAD

**Issue by Xylobryte7** [MiSTer-devel/GBA_MiSTer#68]
Certain points in game won’t load because “it won’t play on this hardware.

**Comment by RobertPeip** [comment]
Maybe the common Sram/EEprom trick. I will try to add them to the exception list and see if it helps.

**Comment by RobertPeip** [comment]
Both games work for quiet some time without a problem. Please provide a savestate for each game at a place BEFORE the problem occurs so i can test if the fix works. Thanks

**Comment by SegaSnatcher** [comment]
Maybe he's using the Matt Bios?

**Comment by RobertPeip** [comment]
As the other Dragonball games do use the SRam copyprotection check and we already have an exception for these, i assume the newer ones also do. They probably just trigger later to annoy the player.

However, i don't want to just add in the gamecodes without testing. So if you want to play ahead, just upload savestates and if it's really just this check, i will upload a fix few hours later. I guess that's fair enough.

**Comment by VickiViperZabel** [comment]
Checked both Legacy of Goku 2 and Buu's Fury on the 20200617 release and can confirm the anti-piracy method triggers on both.

I've prepared savestates at the trigger points for each game
[LOG2+BuusFuryAPTriggers.zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/4855220/LOG2%2BBuusFuryAPTriggers.zip)

**Comment by RobertPeip** [comment]
Fixed. When testing, make sure you create a savegame, reboot and load the savegame. Savestates are already tainted.
Testbuild attached.

[GBA_dbz.zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/4866139/GBA_dbz.zip)
