### ISSUE TITLE
Zelda The Minish cap imposible to play

### ISSUE THREAD

**Issue by Michinomiau** [MiSTer-devel/GBA_MiSTer#69]
I've tryed with different core versions and roms, but in the menu always get the same issue, i can´t start nor select nothing.

It's posible to play to this game with the core?

I don't have any problem with other games

![ZElda](https://user-images.githubusercontent.com/53310052/84810535-c2f22780-b00b-11ea-8cf7-1893471e495d.jpg)

**Comment by RobertPeip** [comment]
Please use official Bios. The game does not work with Normmatts Bios.

**Comment by Michinomiau** [comment]
Nice, will try thanks for the help.

**Comment by RobertPeip** [comment]
As the readme says: "Original GBA BIOS can be placed to GBA folder with name boot.rom"

**Comment by Michinomiau** [comment]
Sorry just read it 10 second ago, thanks for your patience.
