### ISSUE TITLE
Alternative mappings seem wrong on PSX Hori Fight Commander

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/GBA_MiSTer#72]
Greetings,

I've tried setting up alternative L, R, start and select buttons on my gamepad, and the mappings (at least for some of those buttons) seems wrong. Pressing my alternative R actually output a Start button press, and pressing my alternative Select seems to trigger a fastforward mode.

Cheers!

**Comment by RobertPeip** [comment]
I just mapped all alternative buttons to original buttons, but alternative Select to new button and both old and new button act as select, so i'm clueless how that happened...

**Comment by Left-Empty** [comment]
It actually seems to happen only on my PSX Hori Fighting Commander. Alternate mappings seem fine in other cores, but not in this one. I will try alternate settings when I got the time.

**Comment by Left-Empty** [comment]
Okay I figured it: the buttons there were duplicates of buttons because of a mapping settings. Since they were physically different buttons, the MiSTer allowed me to map multiple buttons mapping on a single one. It's all the manufacturer's fault!
Sorry for wasting anyone's time.

**Comment by RobertPeip** [comment]
If it's no real bug, i'm fine with it. Have fun :)
