### ISSUE TITLE
Snood (USA) - audible high pitched tone in menus

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/GBA_MiSTer#76]
**Snood (USA).gba** — CRC-32: F1F1F148
In main menu highlighting an option causes a high pitched audio tone to appear which remains constant afterwards. Game loaded to SDRAM, tone is present through both HDMI and I/O board's audio port.
This tone is not present on real hardware to my knowledge.

**Comment by RobertPeip** [comment]
Game is buggy and keeps DMA sound on without providing samples...

I made a fix for this special case.

[GBA_emptyDMASound.zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/5535378/GBA_emptyDMASound.zip)

**Comment by TLPD-AVW** [comment]
Just tested your attached build, Snood is fixed, thanks for quick response!

I also discovered a similar issue in **Advance GTA (Japan) (En) (Rev 1)**, the Japanese version of GT Advance Championship Racing. After finishing a quick race there's a second long loud beep while the screen fades to black and switches from race to menu. Likewise, it is fixed in your provided build, so I guess it was a similar cause.

**Comment by RobertPeip** [comment]
Thanks for checking, will close this

**Comment by Thelypody** [comment]
Unfortunately this bug is present in release 20210718. Just like with issue #109, this issue reappears in release 20210629 and is not present in preceding release 20210415. This issue should probably be reopened, I can't do this on my own as I did not close this issue originally.

**Comment by RobertPeip** [comment]
For some reason i changed back this line in may:

https://github.com/MiSTer-devel/GBA_MiSTer/commit/aaa82231bb6fbf80f4bff7d18c84e966d68a7fdd#diff-115ffefc22f615bc4a93268cc74e4c4e9ca141dc704bd57320eaa8aef402d2baR202

which was the fix for snood. need to look after that.

**Comment by RobertPeip** [comment]
Thanks for finding this! The Sound DMA was really buggy since then. This also lead to the problem in F-Zero climax, becasue the game spends to much time for filling the Fifo, not being able to draw the screen in time.

It's fixed with the latest commit.
