### ISSUE TITLE
Famicom Minis 22-28 and 30 not fixed

### ISSUE THREAD

**Issue by Atmosfear1968** [MiSTer-devel/GBA_MiSTer#82]
According to the changelog of November 20, 2020, the Famicom Minis 22-28 should be fixed, but they are not.
Text and graphics are missing. The same applies to the Famicom Mini 30.

**Comment by wwark** [comment]
Hi,

You need to activate sprite limit option.
https://github.com/MiSTer-devel/GBA_MiSTer#spritelimit

Thanks,

**Comment by RobertPeip** [comment]
Maybe we should force this for games that use extra sprites as "anti emulation" method, as it's not obvious.

**Comment by wwark** [comment]
Yes it is a good idea do not hesitate if you want me to test after this change.

**Comment by RobertPeip** [comment]
done

**Comment by wwark** [comment]
Thank your @RobertPeip !
Great release and it is working great on my side !
