### ISSUE TITLE
Minish Cap does not load file select screen fully

### ISSUE THREAD

**Issue by exodvs** [MiSTer-devel/GBA_MiSTer#84]
When trying to play The Legend of Zelda: The Minish Cap, the three slots of the file select screen are stuck on the left side, fluttering up and down. User input does nothing. The ROM was taken from the Wii U virtual console and is bit-for-bit identical to the one on Vimm. Sonic Advance 2 and Ultimate Spider-Man are the exact same size and exhibit no issues.
https://user-images.githubusercontent.com/36355339/109369875-dc6a9500-7863-11eb-808d-1413aba4cfac.png

**Comment by SegaSnatcher** [comment]
I have no issues playing this game using the standard GBA rom.  I would recommend just use the original rom for now.

You are using the official GBA bios and not the NormMatt bios correct?

**Comment by RobertPeip** [comment]
Image looks exactly like it's taken with build in (Normmatt) BIOS. Please use official BIOS for this game.

**Comment by exodvs** [comment]
> Image looks exactly like it's taken with build in (Normmatt) BIOS. Please use official BIOS for this game.

Danke. Es funktionert jetzt. Ich werde das Problem schließen.

**Comment by Sawtaytoes** [comment]
How do you use the official one instead of Normmatt?
