### ISSUE TITLE
After updating 2/28 GBA core no longer works. 

### ISSUE THREAD

**Issue by Techsteps** [MiSTer-devel/GBA_MiSTer#85]
I was using this core no issues yesterday. Ran the updater today and now the core is not working. I get NO SIGNAL on the monitor, LEDs on the I/O board all stop, and the physical buttons do nothing. Have to power down and back up. Ran with two separate configs. One default and one modified and both respond the same.

**Comment by Techsteps** [comment]
![image](https://user-images.githubusercontent.com/38540600/109435246-86265f00-79e7-11eb-9735-8044604be696.png)

**Comment by SegaSnatcher** [comment]
Look at the size of the .rbf.  Clearly something is wrong with that, so delete all the GBA RBFs and run updater again.

**Comment by Techsteps** [comment]
If you look in the GitHub you can see the newest version is 0bytes.

**Comment by SegaSnatcher** [comment]
Are you doing things manually?    

Well here is the latest release.

https://github.com/MiSTer-devel/GBA_MiSTer/blob/master/releases/GBA_20210227.rbf

**Comment by sorgelig** [comment]
As i see, the file is 4MB on github. So it must be something wrong on your side.

**Comment by Techsteps** [comment]
![08A82EDF-18FF-48F5-A25D-ACC63A737473](https://user-images.githubusercontent.com/38540600/109496267-6ed68880-7a5e-11eb-841e-ebc5b8c6b04b.png)

I don’t see how I could be doing something wrong here. But, okay. Thank you. I’ll figure it out.

**Comment by SegaSnatcher** [comment]
Did you not see my previous post?  

Use this link.

https://github.com/MiSTer-devel/GBA_MiSTer/blob/master/releases/GBA_20210227.rbf

**Comment by Techsteps** [comment]
Isn’t that the file in the screenshot I just posted? 

Thanks

**Comment by SegaSnatcher** [comment]
No.   The file I linked is a 4MB file.   Just click the link and click the download tab.  I don't know why you are having so much trouble.

**Comment by Techsteps** [comment]
I understand that you say its 4mb. But, I literally posted a screenshot
showing what happens when I go to that file. It says "empty file"... its
right in the screenshot I sent.

Don't worry. I appreciate the help. I am going to close this.

**Comment by SegaSnatcher** [comment]
You are doing it wrong, click the download tab in that link.

**Comment by Techsteps** [comment]
Yep. It fails. Thanks for the help.

**Comment by blackjer** [comment]
Just verified, hitting the download button downloads a 4,150KB file that
works without issue.

**Comment by SegaSnatcher** [comment]
@Techsteps Are you clicking this?

![GBARBF](https://user-images.githubusercontent.com/36483667/109517177-9897ab80-7a6e-11eb-9917-e600ae132f81.JPG)

**Comment by sorgelig** [comment]
looks like VPN/Proxy/Browser cached file. So it's need to be purged somehow.

**Comment by Techsteps** [comment]
So, just to confirm. It was a cache issue... on githubs side. Probably a CDN issue or something.
