### ISSUE TITLE
Comparison between Release 20210227 and mGBA 0.9-6805 (mGBA Test Suite r71)

### ISSUE THREAD

**Issue by KawaiiDinosaur** [MiSTer-devel/GBA_MiSTer#86]
Test name | Test Count | Mister GBA | mGBA |
-- | -- | -- | -- |
Memory | 1552 | 1552 | 1552 | 
IOREAD | 123 | 123 | 110 | 
Timing | 1660 | 1606 | 1560 | 
Timer | 936 | 442 | 744 | 
Timer IRQ | 90 | 65 | 70 | 
Shifter | 140 | 140 | 140 | 
Carry | 93 | 93 | 93 | 
BIOSMath | 615 | 615 | 615 | 
DMATests | 1256 | 1248 | 1232 | 
EdgeCase | 10 | 5 | 8 |
Multiply | 72 | 52 | 52 |
Layer Toggle | 1 | pass | fail | 
OAM Update | 1 | fail | fail |

**Comment by SegaSnatcher** [comment]
Yeah, he's aware of where his core sits in terms of accuracy tests.  I don't know what his plans are for the future in terms of accuracy is concerned, but would be cool if further improvements could be made, but currently games seem to run extremely well.

**Comment by RobertPeip** [comment]
Yes the table wasn't updated long time and in the meantime a lot has changed on both the GBA core and mGBA and it's testbench. Also some newer emulators would probably need to be included now.

**Comment by RobertPeip** [comment]
I removed the comparison for the time being. It was not accurate anymore and it doesn't cover newer, more accurate emulators like Nanoboy or Eggvance.
