### ISSUE TITLE
Feature Request: Save and Load States as Mappable Input Buttons

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/GBA_MiSTer#88]
Mr. RobertPiep, thank you for commenting on my Lynx core feature request! You've done a fabulous job being the only MiSTer dev to have save and load states and rewind and fast forward capabilities in your cores. I really appreciate the effort, because I know that adding save/load states isn't trivial in FPGA.

Anyways, I just wanted to ask if you could make the save and load states mappable buttons on the controller like you've done with the Lynx and Game Boy cores? Since the other two cores you've worked on have these mappable buttons, I just wanted the GBA to have it so it's not left out :) Obviously, I can save/load from the menu or keyboard, but it'd be convenient as two buttons, please.

**Comment by RobertPeip** [comment]
Yes, I also missed them recently. Will take care of that the next days.

**Comment by RobertPeip** [comment]
done
