### ISSUE TITLE
Zelda Link to the Past buzzing after rewind

### ISSUE THREAD

**Issue by badvision** [MiSTer-devel/GBA_MiSTer#89]
Anywhere in the game, if I use rewind there is a constant low-frequency buzzing sound that never goes away.  I can save the game, quit to the main menu and then it resets sound and that clears up.  Also if I save state, reset the core, and restore state the buzzing is also present.  I suspect it's something to do with the DAC samples that gets corrupted but I can't quite tell.

**Comment by RobertPeip** [comment]
Not all sound registers are saved in the savestate, because I assumed the sound to fix itself fast. If that's not the case, more registers must be added.
Please upload a savestate that leads to this sound, so I can reproduce it.

**Comment by badvision** [comment]
You got it!  Honestly it is super reproducible if you use the zelda link to the past / four swords, launch link to the past and just hit rewind at any point.  I can reproduce it pretty readily.[https://file.io/BX0ZNj3KTbcm](url) That link will work once, let me know if you need a more semi-permanent copy or if the link goes bad.

**Comment by badvision** [comment]
Also: Thank you for responding so quickly @RobertPeip!!

**Comment by RobertPeip** [comment]
Could reproduce it myself now when it's totally quiet usually: I should be able to see why this happens

**Comment by RobertPeip** [comment]
fixed. You can either build yourself, use a testbuild available on MiSTer discord or wait for the next release

**Comment by badvision** [comment]
Happy to wait but ... damn that was fast.  You rock!  Thanks so much. :)
