### ISSUE TITLE
Sound Issue with Certain game on GBA2P

### ISSUE THREAD

**Issue by Mekiath** [MiSTer-devel/GBA_MiSTer#90]
Played around with a few games now and haven't noticed anything really off as a casual player with the GBA2P but for whatever reason Kidou Senshi Gundam - Seed Destiny has some issues with possibly the sound channel most of the background music and some of the title screen music get effected as a result.

Attaching some video capture I did showing the issue.
https://www.youtube.com/watch?v=2zOCw8Zz4Fg

**Comment by RobertPeip** [comment]
Thanks for reporting!
Bug is fixed with the new release.
