### ISSUE TITLE
Video/Sound

### ISSUE THREAD

**Issue by aihooo444** [MiSTer-devel/GBA_MiSTer#91]
with newest release I get no video or sound i have to reset mister every time i have tried with my current setup and a fresh mister ini file and still will not load once i revert back to last release everything works fine

**Comment by RobertPeip** [comment]
Could you try to modify your mister.ini please?
Please add the lines:

[GBA]
vsync_adjust=2

If it works, please look for the "Sync core to video" option in Video/Audio" and set to "On".
If it doesn't work, the RBF you downloaded is most likely corrupt.

**Comment by aihooo444** [comment]
Sorry just got around to this, no vsync_adjust=2 did not work still no video or audio i redownloaded the rbf twice and it still does not work even with default mister.ini

**Comment by aihooo444** [comment]
The mister does not freeze it just has no video so i can blind navigate through the menus if I knew what to press, could you tell me exactly which buttons to press to turn on sync core to video

**Comment by RobertPeip** [comment]
Sync on Video is on per default in the newest release, so this cannot be the reason.

**Comment by aihooo444** [comment]
Do you know anything else i can try? I am at a loss the old rbf works fine and all other cores work.

**Comment by aihooo444** [comment]
not sure what happened i just took out sd card and put it back in and now works thanks

**Comment by aihooo444** [comment]
Ok so after i restarted the mister the problem returned but I did not want to bother you with it anymore since it seemed like I was the only one having a problem but i saw the new test build you posted on the discord and now the issue is resolved everything is working fine with the new test build.

**Comment by RobertPeip** [comment]
Sounds like you are using some Video out or sensitive TV that might be on the edge with timing.
Glad the version works better for you.

**Comment by aihooo444** [comment]
Hey just a quick follow up it was my HDMI cord I replaced it with a new one and all is good now 100% thanks for your hard work
