### ISSUE TITLE
GBA2P - Scale: H-Integer

### ISSUE THREAD

**Issue by Gikkman** [MiSTer-devel/GBA_MiSTer#94]
First off, I gotta say that the GBA2P is an awesome feature and super fun! My wife and I really really enjoy playing Four Swords together.

I was wondering if it'd be possible to allow scaling on H-Integer? I noticed we could use V-Integer to scale, and that looks pretty nice on Split: Vert. But if we wanted something similar for Split: Hori, there is no option to scale on H-Integer without also scaling on V (which looks really odd on a 16:9 TV).

I'd appreciate it, but if ain't possible or too much work, no worries. Awesome job irregardless.

// Gikkman

**Comment by RobertPeip** [comment]
Sorry, i never looked at what these additional Integer scaling modes really do, as i always just use pure integer scaling with vscale_mode=1 in the mister.ini.

Can you explain what you really want to reach? A picture might help a lot.

**Comment by Gikkman** [comment]
I feel really silly now, but the problem I had was that when we had the pictures horizontally, some pixels were cut of on both left and right side. However, it turns out my TV has some kind of "smart picture mode" where it zoomed in a bit depending on the image (thanks modern technology....). Once I turned it off I can see the full picture. Sorry for taking up your time.
