### ISSUE TITLE
Small visual glitch in ALttP

### ISSUE THREAD

**Issue by RichEsq** [MiSTer-devel/GBA_MiSTer#96]
When playing A Link to the Past, at the "Choose a File" menu, press right on the D Pad on a selected game file. An options menu will appear allowing the user to choose the text speed and brightness. There is a small visual glitch on the lower left of this options menu in the form of a blinking vertical line.

This one seems easy to replicate, but please let me know if I can provide more information. 

Thanks for all your great work!

**Comment by RobertPeip** [comment]
Cannot reproduce this at all. 
Tried with original BIOS, Homebrew BIOS, EU and US Version and all 3 save places. Nothing blinking here.

SHA1 of US-ROM for you to verify: A272055ABBBF6C26B0CD54C87395D01699589161

![20210714_061622-Legend of Zelda, The - A Link To The Past Four Swords (U)  !](https://user-images.githubusercontent.com/53250236/125572733-53e2a177-e5d3-4c4c-9750-66cd7d17250e.png)

**Comment by RichEsq** [comment]
How exceedingly strange. Occurs reliably for me in the US Rom (same SHA1) on screen, but it doesn't appear in screenshots.

Photo and screenshots attached. 
![20210714_072648-Legend of Zelda, The - A Link to the Past   Four Swords (USA, Australia)](https://user-images.githubusercontent.com/10680951/125581163-6b6fca87-c32c-495b-811c-183f703e4553.png)

![IMG_4828](https://user-images.githubusercontent.com/10680951/125581427-0ab85a37-4493-4d78-bc2d-917665639477.jpg)

**Comment by RichEsq** [comment]
Also occurs using the homebrew bios,

**Comment by wwark** [comment]
Reproduce also on my side. Good catch !
It is not present on the real hardware.
[Legend of Zelda, The - A Link to the Past & Four Swords (USA).zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/6814456/Legend.of.Zelda.The.-.A.Link.to.the.Past.Four.Swords.USA.zip)

**Comment by SegaSnatcher** [comment]
I reproduced the glitch as well.

**Comment by RobertPeip** [comment]
Can reproduce it with the savegame from RichEsq, will try to see what this is

**Comment by wwark** [comment]
I tested previous RBF. This issue is introduce at this version GBA_20200409.rbf.
Previous versions don't have this glitch.

**Comment by RobertPeip** [comment]
Thanks for researching @wwark!

I found the problem. 
It's due to a change in a commit from 08.04.2020 not covering all possible paths from a change in 12.12.2019.
Sometimes things haunt you for years :)

It's a small edge case, but could hit any game.

Lastest commit should fix it. At least it does for me. 
Testbuild attached.

Thanks to everyone for finding, reporting and testing!

[GBA_alttp_sprites.zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/6816079/GBA_alttp_sprites.zip)

**Comment by wwark** [comment]
Thank you @RobertPeip for the quick fix. It fixed it also on my side !
Thanks again @RichEsq to report this issue
