### ISSUE TITLE
Flickerblend

### ISSUE THREAD

**Issue by diettelo** [MiSTer-devel/GBA_MiSTer#97]
If i set Flickerblend to blend and save on the next boot it will be off again.
Same rom.

Funny part is: set to blend loaded rom,
rebootet mister. Loaded gba core.
before loading rom it is blend saved.
after loading rom it turnes off again.

**Comment by RobertPeip** [comment]
Good find...the first Flickerblend bit is cleared when loading a ROM, like the turbo selection. 

This is a leftover from Tilt on Analogstick using that bit, that is removed now...will fix it.

**Comment by RobertPeip** [comment]
Fixed. Testversion attached.

[GBA_flickerblend_reset.zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/6836584/GBA_flickerblend_reset.zip)

**Comment by diettelo** [comment]
will this get in pubkuc release?

**Comment by RobertPeip** [comment]
Made a release from it. Last fix was also not released so it's worth it.

**Comment by diettelo** [comment]
ohh thx. i can test it maybe tomorrow the test build
