### ISSUE TITLE
Games on cifs/smb mounted drives no longer load

### ISSUE THREAD

**Issue by kimbapslice** [MiSTer-devel/GBA_MiSTer#98]
Release 20210415 was the last release that works with games stored on cifs/smb mounted drives. I can see and select the games and it appears to load, but then stays stuck on the "Gameboy" bios. I think the fast loading feature might have broken cifs/smb loading. Other cores are working correctly loading from cifs/smb (megacd, pcegine, etc). I can run Release 20210415 and games will work again. I normally run the update_all script.

using boot.rom original bios and 128MB RAM

**Comment by sorgelig** [comment]
i think only developer who uses cifs/smb may debug and find the source of issue. Problem is most likely on the linux side(HPS) - Main. 
Keep in mind, while network storage may work, it's not advertised and not official feature of MiSTer.

**Comment by Kitrinx** [comment]
Could you elaborate more on what your network scenario is? LAN or WiFi? What type of NAS, and what kind of bandwidth does it have?

**Comment by kimbapslice** [comment]
> 
> 
> Could you elaborate more on what your network scenario is? LAN or WiFi? What type of NAS, and what kind of bandwidth does it have?

Hello, I have an external usb3.0 hdd connected to my EA8500 Linksys router acting as the NAS. I am hardwired via ethernet to the router.

In cifs_mount.sh, I have the option 
ADDITIONAL_MOUNT_OPTIONS="vers=1.0"
so mister could work with the NAS SMB.

In regards to sorgelig, I completely forgot that the cifs/smb is unofficial since I have been using it for so long. Thank-you for all that you've done!

**Comment by Kitrinx** [comment]
I tested several different games off my NAS with no obvious issues with the most current GBA core, mounted via LAN from an unraid server. If you have other (not external) drives which might be faster in your NAS, does it make any difference loading from them?

**Comment by kimbapslice** [comment]
I tested it by mount a shared drive on my Windows 10 machine and got it to work correctly over network. I am closing this ticket since it it related to my specific and old NAS. Thanks for your help everyone!
